packages:
  #
  - "apps/*"
  #
  - "packages/@1/modules/*/*/.react-email"
  - "packages/@1/modules/*/*"
  - "packages/@1/*/*"
  - "packages/@douglasduteil/*"
  - "packages/@douglasduteil/config/*"
  #
  - "turbo/generators"
