#

name: Deploy Strapi to Heroku

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: "deploy.strapi"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Strapi to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: toctoc-admin
          heroku_email: ${{ secrets.HEROKU_EMAIL  }}
          appdir: "targets/admin"
