#
name: E2E
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  APP_URL: "http://localhost:3000"
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
  DO_NOT_TRACK: 1
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  e2e:
    name: End to end testing
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - run: docker compose up --build --detach

      - name: "🔺️  Cache"
        uses: ./.github/actions/cache
        with:
          name: e2e

      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install dependencies
        uses: cypress-io/github-action@7271bed2a170d73c0b08939cd192db51a1c46c50 # v6.7.10
        with:
          runTests: false

      - run: pnpm run build
      - run: docker compose up --wait
      - run: pnpm --filter @1.infra/database exec prisma migrate deploy
      - run: pnpm exec turbo run build

      - name: Cypress run
        uses: cypress-io/github-action@7271bed2a170d73c0b08939cd192db51a1c46c50 # v6.7.10
        env:
          CONSOLA_LEVEL: "2"
          DEPLOY_ENV: "production"
          NODE_ENV: "development"
        with:
          install: false
          start: pnpm start
          working-directory: apps/e2e
          spec: features/${{ matrix.e2e_test }}

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: failure()
        with:
          compression-level: 9
          name: cypress-screenshots-${{ github.run_number }}
          path: apps/e2e/cypress/screenshots

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: failure()
        with:
          compression-level: 9
          name: cypress-videos-${{ github.run_number }}
          path: apps/e2e/cypress/videos

      - if: failure()
        run: docker compose logs
      - if: always()
        run: docker compose down --volumes --remove-orphans

    strategy:
      matrix:
        e2e_test:
          - auth
          - exchanges
          - forum
          - legal
          - moderation
          - opportunity
          - partner
          - status
          - studient
          - studient_inbox
          - who

  system:
    name: System testing
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json

      - name: "🔺️  Cache"
        uses: ./.github/actions/cache
        with:
          name: system

      - run: pnpm --filter=!e2e install --frozen-lockfile --prefer-offline
      - run: pnpm exec turbo build --filter api...
      - name: Install bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      - run: pnpm test
