#
name: E2E
on:
  push:
  workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  APP_URL: "http://localhost:3000"
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
  DO_NOT_TRACK: 1
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  e2e:
    name: End to end testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - run: docker compose up --build --detach

      - name: "🔺️  Cache"
        uses: ./.github/actions/cache
        with:
          name: e2e

      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm exec cypress install
        working-directory: apps/e2e

      - run: pnpm run build
      - run: docker compose up --wait
      - run: pnpm --filter @1.infra/database exec prisma migrate deploy

      - name: Cypress run
        uses: cypress-io/github-action@0da3c06ed8217b912deea9d8ee69630baed1737e # v6.7.6
        env:
          CONSOLA_LEVEL: "2"
          DEPLOY_ENV: "production"
          NODE_ENV: "development"
        with:
          install: false
          start: pnpm start
          working-directory: apps/e2e
          spec: features/${{ matrix.e2e_test }}

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: failure()
        with:
          compression-level: 9
          name: ${{ matrix.e2e_test }}-cypress-screenshots-${{github.head_ref}}-
          path: apps/e2e/cypress/screenshots

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: failure()
        with:
          compression-level: 9
          name: ${{ matrix.e2e_test }}-cypress-videos-${{github.head_ref}}-
          path: apps/e2e/cypress/videos

      - if: failure()
        run: docker compose logs
      - if: always()
        run: docker compose down --volumes --remove-orphans

    strategy:
      matrix:
        e2e_test:
          - auth
          - exchanges
          - forum
          - opportunity
          - status
          - studient

  system:
    name: System testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json

      - name: "🔺️  Cache"
        uses: ./.github/actions/cache
        with:
          name: system

      - run: pnpm --filter=!e2e install --frozen-lockfile --prefer-offline
      - run: pnpm exec turbo build --filter api...
      - name: Install bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      - run: pnpm test
